config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'experts#index', as: 'search_experts'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
				    registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home', as: "home"
  get '/role', to: 'pages#role', as: "role"
  get '/privacy_policy', to: 'pages#rule', as: "rules"
  get "/pages/:page", to: "pages#show", as: 'page'
  resources :comments
  resources :patients, only: [:index]
  resources :experts, only: [:show, :index, :edit, :update] do
    resources :events, only: [:index, :new, :create, :show, :update] do
      collection do
       get 'check_time'
      end
    end
  end
  resources :users do
    resources :cards, only: [:show, :edit, :update] do
      resources :protocols, only: [:new, :create, :show]
    end
    resources :events, only: [:index, :show, :update]
    resources :vaccines, only: [:show, :edit, :update]
    resources :children do
      resources :vaccines, only: [:show, :edit, :update]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :experts, through: :events
  has_many :children, dependent: :destroy
  has_one :vaccine, dependent: :destroy
  has_one :expert, dependent: :destroy
  has_one :card, dependent: :destroy

  enum role: %i[patient doctor]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
      name: access_token.info.name,
      email: data['email'],
      image: access_token.info.image,
      password: SecureRandom.hex(8))
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
require 'open-uri'
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    cookies[:user_type] = params[:user][:type]
    redirect_to user_google_oauth2_omniauth_authorize_path
  end

  def edit; end

  def update
    case params[:user][:type]
    when 'doctor'
      @user.doctor!
      assign_image_doctor
    else
      @user.patient!
      assign_image_patient
    end
    redirect_to home_path
  end

  private

  def assign_image_doctor
    @expert = assign_expert
    @expert.image.attach(io: File.open('app/assets/images/doctor0.png'), filename: 'doctor0.png')
  end

  def assign_image_patient
    @card = assign_card
    @card.image.attach(io: File.open('app/assets/images/avatar.png'), filename: 'avatar.png')
    assign_vaccine
  end

  def assign_expert
    Expert.create!(full_name: @user.name, category: Category.first, user: @user, level: Level.first)
  end

  def assign_card
    Card.create(user_id: @user.id, birthday: Time.now.strftime('%d/%m/%Y'), full_name: @user.name)
  end

  def assign_vaccine
    Vaccine.create(user_id: @user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :find_user, only: %i[show]

  def show
    @user_fields_hash = {
      fio: @user.expert.full_name,
      category: @user.expert.category.name,
      description: @user.expert.description,
      level: @user.expert.level.name,
      experience: @user.expert.experience,
      education: @user.expert.education,
      add_education: @user.expert.additional_education,
      center: @user.expert.medical_center,
      procedure: @user.expert.procedure,
      phone: @user.expert.phone
    }
  end

  private

  def find_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_fields(key, val)
    @user_keys = {
      fio: 'ФИО',
      category: 'Категория',
      description: 'Краткое описание',
      level: 'Уровень категории',
      experience: 'Опыт',
      education: 'Образование',
      add_education: 'Дополнительное образование',
      center: 'Место работы',
      procedure: 'Процедуры',
      phone: 'Телефон'
    }

    content_tag(:p) do
      content_tag(:strong) do
        "#{@user_keys[key]}: " + val.to_s
      end
    end
  end
end

app/views/users/_doctor.html.erb
<div class="container">
  <h3 class="text-center text-primary pt-4 pb-3">Профиль врача</h3>
  <div class="pacient-card bg-primary-light d-flex flex-column align-items-center row">
    <div class="text-center">
      <%= image_tag(@user.expert.image.url || @user.image, size: 250, class: 'text-center img-fluid mt-4') %>
    </div>
    <div class="m-auto">
      <div class="pacient-card-info bg-primary p-4 text-white m-3 row">
        <div class="d-flex flex-column">
          <% @user_fields_hash.each do |key, val| %>
            <%= user_fields(key, val) %>
          <% end %>

          <%= render partial: "users/doctor_schedule", locals: { expert: @user.expert } %>

          <div class="pt-3">
            <h4 class="text-center mb-3">Адрес</h4>
            <% if @user.expert.address.present? %>
              <iframe
                width="100%"
                height="400px"
                loading="lazy"
                allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=<%= ENV.fetch("API_KEY") %>
      &q=Черкассы+<%= set_address(@user.expert.address) %>">
              </iframe>
            <% else %>
              <iframe
                width="100%"
                height="400px"
                loading="lazy"
                allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=<%= ENV.fetch("API_KEY") %>
      &q=Черкассы">
              </iframe>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to "Редактировать профиль", edit_expert_path(@user.expert),
                class: "btn btn-light text-primary d-block mb-4 inherit" %>
    <%= link_to "Посмотреть как выглядит профиль со стороны", expert_path(@user.expert),
                class: "btn btn-light text-primary d-block mb-4 inherit" %>
  </div>
</div>

<h3 class="text-center text-primary pt-4 pb-3">Оставленные мне комментарии</h3>
<% if @user.expert.comments.present? %>
  <div class="m-2 d-flex-column">
    <% @user.expert.comments.each do |comment| %>
      <div class="col- p-4 bg-white mb-3 border border-success my-3 card-border">
        <strong class="p-2">
          <%= link_to (comment.user.card.full_name if comment.user.card.present?).presence || comment.user.email,
                      user_card_path(comment.user, comment.user.card),
                      class: "text-success" %>
        </strong>
        <strong class="text-right p-2"><%= render_stars(comment.rating) %></strong>
        <p class="p-3 my-3 border border-success bg-success card-border"><%= comment.body %></p>
        <div class="d-flex justify-content-between">
          <div class="p-2">
            <span>Рекомендация </span>
            <i class="fas fa-thumbs-<%= comment.recommendation ? "up" : "down" %>
               fa-lg text-<%= comment.recommendation ? "success" : "danger" %>"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-center">Комментрии отсутствуют</p>
<% end %>

app/views/users/_doctor_schedule.html.erb
<h4 class="text-center my-4">Рабочие часы</h4>
<div class="row p-0 text-center justify-content-center">
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">ПН</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_monday == expert.hw_end_monday ? "выходной" : expert.hw_start_monday + "-" + expert.hw_end_monday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">ВТ</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_tuesday == expert.hw_end_tuesday ? "выходной" : expert.hw_start_tuesday + "-" + expert.hw_end_tuesday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">СР</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_wednesday == expert.hw_end_wednesday ? "выходной" : expert.hw_start_wednesday + "-" + expert.hw_end_wednesday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">ЧТ</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_thursday == expert.hw_end_thursday ? "выходной" : expert.hw_start_thursday + "-" + expert.hw_end_thursday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">ПТ</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_friday == expert.hw_end_friday ? "выходной" : expert.hw_start_friday + "-" + expert.hw_end_friday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">СБ</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_saturday == expert.hw_end_saturday ? "выходной" : expert.hw_start_saturday + "-" + expert.hw_end_saturday %>
      </small>
    </div>
  </div>
  <div class="col-6 col-sm-4 col-md">
    <div class="m-1 bg-light card-border p-3 m-1">
      <p class="bg-success card-border">ВС</p>
      <small class="text-black-50 m-0 text-nowrap">
        <%= expert.hw_start_sunday == expert.hw_end_sunday ? "выходной" : expert.hw_start_sunday + "-" + expert.hw_end_sunday %>
      </small>
    </div>
  </div>
</div>

app/views/users/_patient.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 offset-md-1">
      <div class="card card-pacient-first">
        <div class="card-header card-pacient text-center">
          Профиль пациента</div>
         <div class="card-body text-center">
          <p><%= image_tag(@user.image , size: "150x150") %></p>
          <p>E-mail:<%= @user.email %></p>
          <p>Birthday:<%= @user.birthday.strftime("%d of %B, %Y") if @user.birthday %></p>
          <%= link_to "Редактировать карту пациента", edit_user_card_path(@user, @user.card),
                      class: "btn btn-success" %><br>
          <%= link_to "Ваша карта вакцинации", user_vaccine_path(@user), class: "btn btn-success" %><br>
          <%= link_to "Редактировать профиль", edit_user_path(@user), class: "btn btn-success" %><br>
          <%= link_to "Дети", user_children_path(@user), class: "btn btn-success" %><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <% if current_user.patient? %>
      <%= render "users/patient", object: @user %>
    <% else %>
      <%= render "users/doctor", object: @user %>
    <% end %>
  </div>
</div>