config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'experts#index', as: 'search_experts'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
				    registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home', as: "home"
  get '/role', to: 'pages#role', as: "role"
  get '/privacy_policy', to: 'pages#rule', as: "rules"
  get "/pages/:page", to: "pages#show", as: 'page'
  resources :comments
  resources :patients, only: [:index]
  resources :experts, only: [:show, :index, :edit, :update] do
    resources :events, only: [:index, :new, :create, :show, :update] do
      collection do
       get 'check_time'
      end
    end
  end
  resources :users do
    resources :cards, only: [:show, :edit, :update] do
      resources :protocols, only: [:new, :create, :show]
    end
    resources :events, only: [:index, :show, :update]
    resources :vaccines, only: [:show, :edit, :update]
    resources :children do
      resources :vaccines, only: [:show, :edit, :update]
    end
  end
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :user
  has_many :protocols, dependent: :destroy
  has_one_attached :image

  validates :birthday, presence: true
  validates :full_name, presence: true, length: {maximum: 40}
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :find_user, only: %i[show]
  before_action :find_expert_card, only: %i[show], if: :find_doctor?
  before_action :find_patient_card, only: %i[show edit update], if: :find_patient?
  before_action :correct_user, only: %i[edit update]

  def show
    @protocols = protocols
  end

  def edit; end

  def update
    if @card.update(permit_params)
      redirect_to user_card_path(current_user, current_user.card), success: 'Ваша карта пациента изменена'
    else
      flash.now[:error] = 'Ваша карта пациента не изменена'
      render 'edit'
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_patient_card
    @card = current_user.card
  end

  def find_expert_card
    @card = @user.card
  end

  def protocols
    if current_user.doctor?
      @card.protocols.where(expert_id: current_user.expert.id)
    else
      @card.protocols
    end
  end

  def permit_params
    params.require(:card).permit(:full_name, :gender, :member, :address,
                                 :comment, :phone, :work, :birthday, :image)
  end
end

app/views/cards/edit.html.erb
<div class="container">
  <% if @card.errors.any? %>
    <div class="alert alert-danger">
      <h6>При редактировании возникли ошибки:</h6>
      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class="text-center text-primary pt-4 pb-3">Редактировать карту пациента</h3>
  <div class="pacient-card bg-primary-light d-flex flex-column align-items-center mb-4 row">
    <%= form_with model: @card, url: user_card_path(current_user, @card), method: 'PUT' do |f| %>
      <div class="text-center">
        <%= image_tag(@card&.image, size: 250, class: 'text-center img-fluid my-4') %>
        <%= f.file_field(:image, title: current_user.card.image.filename.to_s,
                         direct_upload: true,
                         class: "rounded mx-auto d-block form-control w-auto") %>
      </div>
      <div class="pacient-card-info bg-primary p-4 text-white m-4 row">
        <div class="d-flex flex-column">
          <p>
            <strong><%= f.label "ФИО" %></strong>
            <span><%= f.text_field :full_name, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Дата рождения" %></strong>
            <span><%= f.date_field :birthday, max: DateTime.now, class: "form-control" %></span>
          </p>
          <p>
            <strong><%= f.label "Пол" %></strong>
            <span><%= select_tag('card[gender]',
                                 options_for_select([["Мужчина", "Мужчина"], ["Женщина", "Женщина"]]),
                                 class: 'form-control') %></span>
          </p>
          <p>
            <strong><%= f.label "Телефон" %></strong>
            <span><%= f.telephone_field :phone, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Адрес" %></strong>
            <span><%= f.text_area :address, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Место работы" %></strong>
            <span><%= f.text_area :work, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Поручитель" %></strong>
            <span><%= f.text_field :member, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Примечания" %></strong>
            <span><%= f.text_area :comment, class: 'form-control' %></span>
          </p>
        </div>
      </div>
      <%= f.submit "Редактировать карту", class: "btn btn-light text-primary d-block mb-4 m-auto" %>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="container">
  <h3 class="text-center text-primary pt-4 pb-3">Карта пациента</h3>
  <div class="pacient-card bg-primary-light d-flex flex-column align-items-center row">
    <div class="text-center">
      <%= image_tag(@card&.image, size: 250, class: 'text-center img-fluid mt-4') %>
    </div>
    <div class="m-auto">
      <div class="pacient-card-info bg-primary p-4 text-white m-3 row">
        <div class="d-flex flex-column">
          <p>
            <strong>ФИО: </strong>
            <span><%= @card&.full_name %></span>
          </p>
          <p>
            <strong>Дата рождения: </strong>
            <span><%= l @card&.birthday, format: :custom %></span>
          </p>
          <p>
            <strong>Пол: </strong>
            <span><%= @card&.gender %></span>
          </p>
          <p>
            <strong>Телефон: </strong>
            <span><%= @card&.phone %></span>
          </p>
          <p>
            <strong>Адрес: </strong>
            <span><%= @card&.address %></span>
          </p>
          <p>
            <strong>Место работы: </strong>
            <span><%= @card&.work %></span>
          </p>
          <p>
            <strong>Поручитель: </strong>
            <span><%= @card&.member %></span>
          </p>
          <p>
            <strong>Примечания: </strong>
            <span><%= @card&.comment %></span>
          </p>
        </div>
      </div>
    </div>
    <% if current_user.expert.present? %>
      <%= link_to "Создать протокол приема пациента", new_user_card_protocol_path(@card.user, @card),
                  class: "btn btn-light text-primary d-block mb-4 inherit" %>
    <% else %>
      <%= link_to "Редактировать", edit_user_card_path(@card.user, @card),
                  class: "btn btn-light text-primary d-block mb-4 inherit" %>
    <% end %>
  </div>
  <h3 class="text-center text-primary pt-5 pb-3">История приемов</h3>

  <% if @protocols.present? %>
    <% @protocols.each do |protocol| %>
      <div class="border border-secondary my-3 card-border">
        <h5 class="bg-secondary border border-secondary card-border-top text-white px-4 py-3 mb-0">
          Протокол приема № <%= @card.id + protocol.id %>
        </h5>
        <div class="row my-3">
          <div class="col-12 col-md-3 d-flex align-items-center justify-content-center ml-md-5">
            <%= image_tag(protocol.expert&.image, size: 200, class: 'avatar-contain m-3 img-fluid px-md-2') %>
          </div>
          <div class="col-12 col-md-6 text-black-50 d-flex flex-column
         justify-content-center align-items-center align-items-md-start px-4">
            <h5>
              <%= link_to protocol.expert.full_name, expert_path(protocol.expert), class: "text-success" %>
            </h5>
            <p class="text-secondary fs-5"><%= protocol.expert.category.name %></p>
            <p><strong>Диагноз: </strong> <%= protocol.diagnosis %></p>
            <p><strong>Рекоммендации по лечению: </strong><%= protocol.therapy %></p>
            <span class="border border-2 rounded-pill badge bg-primary text-wrap">
             <%= protocol.type_of_inspection == "first_visit" ? "Первичный прием" : "Повторный прием" %>
           </span>
          </div>
          <div class="col-12 col-md-3 d-flex flex-column justify-content-around">
            <div class="mx-2 ">
              <%= link_to "Подробнее", user_card_protocol_path(@card.user, @card, protocol),
                          class: "btn btn-secondary d-block m-3" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="text-center">Протоколы приемов отсутствуют</p>
  <% end %>
</div>