config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'experts#index', as: 'search_experts'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
				    registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home', as: "home"
  get '/role', to: 'pages#role', as: "role"
  get '/privacy_policy', to: 'pages#rule', as: "rules"
  get "/pages/:page", to: "pages#show", as: 'page'
  resources :comments
  resources :patients, only: [:index]
  resources :experts, only: [:show, :index, :edit, :update] do
    resources :events, only: [:index, :new, :create, :show, :update] do
      collection do
       get 'check_time'
      end
    end
  end
  resources :users do
    resources :cards, only: [:show, :edit, :update] do
      resources :protocols, only: [:new, :create, :show]
    end
    resources :events, only: [:index, :show, :update]
    resources :vaccines, only: [:show, :edit, :update]
    resources :children do
      resources :vaccines, only: [:show, :edit, :update]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto text-center py-3 bg-primary">
  <div class="container-fluid row d-flex justify-content-around align-items-center">
    <div class="col-12 col-md-4 order-md-1 order-3">
      <h2 class="pl-2 m-0 text-uppercase mt-md-0 mt-3">
        <%= link_to (image_tag "logo-footer.png", class: "p-1", width: "200"),
                    home_path, class: "navbar-brand text-decoration-none fs-4" %>
      </h2>
    </div>
    <div class="col-6 col-md-4 order-md-2 order-2">
      <ul class="list-unstyled d-md-inline-flex m-0">
        <li>
          <%= link_to "О нас", page_path(page: 'about'), class: "nav-link fs-5" %>
        </li>
        <li>
          <%= link_to "Новости", page_path(page: 'news'), class: "nav-link fs-5" %>
        </li>
      </ul>
    </div>
    <div class="col-6 col-md-4 text-white order-md-3 order-1 ">
      <h5 class="text-uppercase m-0">Звоните нам</h5>
      <p class="font-weight-bold">пн.-вс.: с 8:00 до 20:00</p>
      <div class="d-flex flex-column">
        <ul class="list-unstyled">
          <li>
            <%= link_to "(095)337 07 07", "tel:#{+380953370707}" %>
          </li>
          <li>
            <%= link_to "(063)337 07 07", "tel:#{+380633370707}" %>
          </li>
          <li>
            <%= link_to "(067)337 07 07", "tel:#{+380673370707}" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="text-white">
    <%= link_to "Политика конфиденциальности", page_path(page: 'rule') %>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <h2 class="pl-2 m-0 text-uppercase">
    <%= link_to (image_tag "logo.png", class: "p-1", width: "180"),
                home_path, class: "navbar-brand text-decoration-none fs-4 bg-white" %>
  </h2>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item px-2">
        <%= link_to "Найти врача", search_experts_path,
                    class: "btn btn-secondary btn-sm d-block mb-1" if user_signed_in? && current_user.patient? %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to "Профиль", user_path(current_user),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.doctor? %>
        </li>
        <li class="nav-item">
          <%= link_to "Записи на прием", expert_events_path(current_user.expert),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.doctor? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Пациенты", patients_path,
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.doctor? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Записи на прием", user_events_path(current_user),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.patient? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Карта пациента", user_card_path(current_user, current_user.card),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.patient? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Карта вакцинации", user_vaccine_path(current_user, current_user.id),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.patient? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Дети", user_children_path(current_user),
                      class: "btn btn-success btn-sm mx-2 d-block mb-1" if current_user.patient? %>
        </li>
        <li class="nav-item ">
          <%= link_to "Новости", page_path(page: 'news'),
                      class: "btn btn-secondary btn-sm mx-2 d-block mb-1" %>
        </li>
      <% end %>
    </ul>
    <div>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item ">
            <%= link_to "Выйти", destroy_user_session_path, method: :delete,
                        class: "btn btn-danger btn-sm mx-2 d-block mb-1" %>
          </li>
        <% else %>
          <li class="nav-item ">
            <%= link_to "Зарегистрироваться", new_user_registration_path,
                        class: "btn btn-primary btn-sm mx-2 d-block mb-1" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Войти", user_session_path,
                        class: "btn btn-primary btn-sm mx-2 d-block mb-1" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
<head>
  <title>MedHelper</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <% if Rails.env.production? %>
    <meta name="google-site-verification" content="X6zgbF3iD6LmVdqIVtJboyt7ddTXHeHSrtqjmMy1EPE"/>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
  <% end %>
</head>

<body class="d-flex flex-column h-100">
<%= render 'layouts/navbar' %>
<div class="pt-3 mt-5">
  <div class="col-12 text-center">
    <% flash.each do |name, message| %>
      <p class="alert alert-hidden alert-<%= name %>">
        <%= message %>
      </p>
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
<%= render 'layouts/footer' %>
</html>