config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'experts#index', as: 'search_experts'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
				    registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home', as: "home"
  get '/role', to: 'pages#role', as: "role"
  get '/privacy_policy', to: 'pages#rule', as: "rules"
  get "/pages/:page", to: "pages#show", as: 'page'
  resources :comments
  resources :patients, only: [:index]
  resources :experts, only: [:show, :index, :edit, :update] do
    resources :events, only: [:index, :new, :create, :show, :update] do
      collection do
       get 'check_time'
      end
    end
  end
  resources :users do
    resources :cards, only: [:show, :edit, :update] do
      resources :protocols, only: [:new, :create, :show]
    end
    resources :events, only: [:index, :show, :update]
    resources :vaccines, only: [:show, :edit, :update]
    resources :children do
      resources :vaccines, only: [:show, :edit, :update]
    end
  end
end

app/models/expert.rb
# frozen_string_literal: true

class Expert < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :users, through: :events
  belongs_to :category
  belongs_to :user
  belongs_to :level, optional: true
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :protocols, dependent: :destroy

  validates :category, presence: false

  scope :searcher, lambda { |params|
    search_scope = Expert.all
    search_scope = search_scope.query(params[:query]) if params[:query].present?
    search_scope = search_scope.filters(params[:filter]) if params[:filter].present?
    search_scope
  }
  scope :query, lambda { |params|
    where('full_name ILIKE :search', search: "%#{params}%")
      .or(where(category_id: Category.where('name ILIKE :search', search: "%#{params}%").ids))
  }
  scope :filters, lambda { |parameter|
    case parameter
    when 'upexperience'
      order(experience: :asc)
    when 'downexperience'
      order(experience: :desc)
    when 'upcategory'
      order(level_id: :desc)
    else
      order(level_id: :asc)
    end
  }

  def rating
    return 0 if comments.empty?
    comments.sum(&:rating).to_f / comments.count
  end
end

app/controllers/experts_controller.rb
# frozen_string_literal: true

class ExpertsController < ApplicationController
  before_action :find_expert, only: %i[show edit update]
  before_action :correct_expert, only: %i[edit update]
  before_action :find_all_level, :find_all_category, only: %i[edit update]

  def index
    @experts = Expert.searcher(params).paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def edit; end

  def update
    if @expert.update(expert_params)
      redirect_to @expert.user, success: 'Ваш профиль был изменён'
    else
      flash.now[:danger] = 'Ваш профиль не был изменён'
      render :edit
    end
  end

  private

  def find_expert
    @expert = Expert.find(params[:id])
  end

  def find_all_level
    @level = Level.all
  end

  def find_all_category
    @category = Category.all
  end

  def expert_params
    params.require(:expert).permit(:full_name, :description, :experience,
                                   :additional_education, :procedure, :address,
                                   :medical_center, :phone, :hw_start_monday,
                                   :hw_end_monday, :hw_start_tuesday,
                                   :hw_end_tuesday, :hw_start_wednesday,
                                   :hw_end_wednesday, :hw_start_thursday,
                                   :hw_end_thursday, :hw_start_friday,
                                   :hw_end_friday, :hw_start_saturday, :image,
                                   :hw_end_saturday, :hw_start_sunday, :level_id,
                                   :hw_end_sunday, :category_id, :education)
  end
end

app/helpers/experts_helper.rb
# frozen_string_literal: true

require 'time'
module ExpertsHelper
  def set_address(address)
    address.split(' ').join('+')
  end

  def selector_element(arr)
    arr.each_with_index.map { |x, i| [x.name, i + 1] }
  end

  def set_time
    (0..23).map { |x| %W[#{x}:00 #{x}:00] }
  end
end

app/views/experts/_modal_contact.html.erb
<div class="modal fade bd-example-modal-lg-<%= expert.id %>"
     tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-secondary">
        <h5 class="modal-title text-white">Контакты</h5>
        <button type="button" class="close bg-secondary modal-button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-7">
            <% if expert.address.present? %>
              <iframe
                width="460"
                height="470"
                style="border:0"
                loading="lazy"
                allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=<%= ENV.fetch("API_KEY") %>
                          &q=Черкассы+<%= set_address(expert.address) %>">
              </iframe>
            <% else %>
              <iframe
                width="460"
                height="470"
                style="border:0"
                loading="lazy"
                allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=<%= ENV.fetch("API_KEY") %>
                          &q=Черкассы">
              </iframe>
            <% end %>
          </div>
          <div class="col-sm-5">
            <h5 class="text-center text-primary">Адрес</h5>
            <p class="text-center text-secondary"><%= expert.address.presence || "Нет информации" %></p>
            <h5 class="text-center text-primary">Телефон</h5>
            <p class="text-center text-secondary">
              <% if expert.phone.present? %>
                <%= link_to "#{expert.phone}", "tel:#{expert.phone}", class: "text-secondary" %>
              <% else %>
                Нет информации
              <% end %>
            </p>
            <h5 class="text-center text-primary">Время работы</h5>
            <p class="text-center text-secondary">Пн: <%= expert.hw_start_monday %>-<%= expert.hw_end_monday %></p>
            <p class="text-center text-secondary">Вт: <%= expert.hw_start_thursday %>
              -<%= expert.hw_end_thursday %></p>
            <p class="text-center text-secondary">Ср: <%= expert.hw_start_wednesday %>
              -<%= expert.hw_end_wednesday %></p>
            <p class="text-center text-secondary">Чт: <%= expert.hw_start_tuesday %>
              -<%= expert.hw_end_tuesday %></p>
            <p class="text-center text-secondary">Пт: <%= expert.hw_start_friday %>-<%= expert.hw_end_friday %></p>
            <p class="text-center text-secondary">Сб: <%= expert.hw_start_saturday %>
              -<%= expert.hw_end_saturday %></p>
            <p class="text-center text-secondary">Вс: <%= expert.hw_start_sunday %>-<%= expert.hw_end_sunday %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experts/edit.html.erb
<div class="container">
  <% if @expert.errors.any? %>
    <div class="alert alert-danger">
      <h6>При редактировании возникли ошибки:</h6>
      <ul>
        <% @expert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class="text-center text-primary pt-4 pb-3">Редактировать профиль</h3>
  <div class="pacient-card bg-primary-light d-flex flex-column align-items-center mb-4 row">
    <%= form_with model: @expert, method: :put do |f| %>
      <div class="text-center">
        <%= image_tag @expert.image.url || current_user.image, size: 250, class: 'text-center img-fluid my-4' %>
        <%= f.file_field(:image, direct_upload: true,
                         class: "rounded mx-auto d-block form-control w-auto") %>
      </div>
      <div class="pacient-card-info bg-primary p-4 text-white m-4 row">
        <div class="d-flex flex-column">
          <p>
            <strong><%= f.label "ФИО" %></strong>
            <span><%= f.text_field :full_name, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Категория" %></strong>
            <span><%= select_tag('expert[category_id]',
                                 options_for_select(Category.all.map { |category| [category.name, category.id] },
                                                    @expert.category.id), class: 'select form-control') %>
            </span>
          </p>
          <p>
            <strong><%= f.label "Уровень" %></strong>
            <span><%= select_tag('expert[level_id]',
                                 options_for_select(Level.all.map { |level| [level.name, level.id] },
                                                    @expert.level.id), class: 'select form-control') %>
            </span>
          </p>
          <p>
            <strong><%= f.label "Краткое описание:" %></strong>
            <span><%= f.text_area :description, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Опыт:" %></strong>
            <span><%= number_field_tag 'expert[experience]', "#{current_user.expert.experience}",
                                       in: 0...99,
                                       class: 'form-control' %>
            </span>
          </p>
          <p>
            <strong><%= f.label "Образование" %></strong>
            <span><%= f.text_area :education, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Дополнительное образование:" %></strong>
            <span><%= f.text_area :additional_education, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Процедуры:" %></strong>
            <span><%= f.text_area :procedure, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Место работы:" %></strong>
            <span><%= f.text_area :medical_center, class: 'form-control' %></span>
          </p>
          <p>
            <strong><%= f.label "Адрес:" %></strong>
            <span><%= f.text_field :address,
                                   placeholder: "улица Смелянская, 132, Черкассы",
                                   class: 'form-control' %>
            </span>
          </p>
          <p>
            <strong><%= f.label "Teлефон:" %></strong>
            <span><%= f.telephone_field :phone, class: 'form-control' %></span>
          </p>
          <div class="fs-5">
            <h4 class="pt-3 text-center">График работы:</h4>
            <p class="py-2">Понедельник:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_monday]', options_for_select(set_time, @expert.hw_start_monday),
                               class: 'form-control') %>
                <% @expert.errors.full_messages_for(:hw_start_monday).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_monday]', options_for_select(set_time, @expert.hw_end_monday),
                               class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Вторник:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_tuesday]', options_for_select(set_time, @expert.hw_start_tuesday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_tuesday]', options_for_select(set_time, @expert.hw_end_tuesday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Среда:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_wednesday]', options_for_select(set_time, @expert.hw_start_wednesday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_wednesday]', options_for_select(set_time, @expert.hw_end_wednesday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Четверг:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_thursday]', options_for_select(set_time, @expert.hw_start_thursday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_thursday]', options_for_select(set_time, @expert.hw_end_thursday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Пятница:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_friday]', options_for_select(set_time, @expert.hw_start_friday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_friday]', options_for_select(set_time, @expert.hw_end_friday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Cуббота:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_saturday]', options_for_select(set_time, @expert.hw_start_saturday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_saturday]', options_for_select(set_time, @expert.hw_end_saturday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
            <hr>
            <p class="py-2">Воскресенье:</p>
            <div class="row text-center">
              <div class="col-sm-1">
                <span>C</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_start_sunday]', options_for_select(set_time, @expert.hw_start_sunday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
              <div class="col-sm-1">
                <span>До</span>
              </div>
              <div class="col-sm-5">
                <%= select_tag('expert[hw_end_sunday]', options_for_select(set_time, @expert.hw_end_sunday), class: 'form-control') %>
                <% @expert.errors.full_messages_for(:phone).each do |message| %>
                  <div class="alert alert-warning alert-event"><%= message %></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit "Редактировать карту", class: "btn btn-light text-primary d-block mb-4 m-auto" %>
    <% end %>
  </div>
</div>

app/views/experts/index.html.erb
<div class="container">
  <h3 class="text-center text-primary pt-4 pb-3">Поиск врача</h3>
  <% if flash[:notice] %>
    <div class="notice alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <div class="border border-success my-3 card-border p-3 bg-success text-center">
    <div class="row">
      <div class="col-12 col-md-8 mb-2 mb-md-0">
        <%= form_tag(search_experts_path, method: :get) do %>
          <%= search_field_tag :query, params[:query],
                               data: { autocomplete_source: Category.pluck(:name) + Expert.pluck(:full_name) },
                               placeholder: "Введите фамилию врача или категорию",
                               class: "form-control input-lg text-black-50",
                               id: "search" %>
        <% end %>
      </div>
      <div class="col-12 col-md-4">
        <%= form_tag(search_experts_path, method: :get) do %>
          <%= select_tag :filter, options_for_select(["Сортировать по",
                                                      ["От высшей категории к низшей", "downcategory"],
                                                      ["От низшей категории к высшей", "upcategory"],
                                                      ["От большого стажа к небольшому", "downexperience"],
                                                      ["От небольшого стажа к большому", "upexperience"]]),
                         class: 'form-control selector text-black-50' %>
        <% end %>
      </div>
    </div>
  </div>
  <% @experts.each do |expert| %>
    <div class="border border-success my-3 card-border">
      <div class="row my-3">
        <div class="col-12 col-md-3 d-flex align-items-center justify-content-center ml-md-5">
          <%= image_tag(expert.image.url || current_user.image, size: 200, class: "img-fluid px-md-2") %>
        </div>
        <div class="col-12 col-md-6 text-black-50 d-flex flex-column
         justify-content-center align-items-center align-items-md-start px-4">
          <h5>
            <%= link_to expert.full_name, expert_path(expert), class: "text-success" %>
            <i class='fas fa-star gold-star'></i><%= expert.rating %>
          </h5>
          <small>Отзывов: <%= expert.comments.count %></small>
          <p class="text-secondary fs-5"><%= expert.category.name %></p>
          <p><strong><%= expert.level.name %></strong></p>
          <div class="d-inline-block">
            <span class="badge rounded-pill bg-success"><%= expert.experience %></span>
            <span> лет опыта</span>
          </div>
          <%= truncate(expert.description, length: 140, separator: '...') %>
        </div>
        <div class="col-12 col-md-3 d-flex flex-column justify-content-around">
          <div class="mx-2 ">
            <%= link_to(new_expert_event_path(expert), method: :get, class: "btn btn-success w-100 mt-3") do %>
              <i class="fa fa-calendar mx-2"></i>Записаться
            <% end %>
            <%= button_tag data: { toggle: "modal",
                                   target: ".bd-example-modal-lg-#{expert.id}" },
                           class: "btn btn-primary text-white w-100 mt-3" do %>
              <i class="fas fa-phone-alt mx-2"></i>Контакты
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'modal_contact', expert: expert %>
  <% end %>
</div>
<%= will_paginate @experts, class: "pagination justify-content-center my-3",
                  previous_label: '<i class="fas fa-arrow-left"></i>',
                  next_label: '<i class="fas fa-arrow-right"></i>' %>

app/views/experts/show.html.erb
<div class="container">
  <h3 class="text-center text-primary pt-4 pb-3"><%= @expert.full_name %></h3>
  <div class="border border-success my-3 card-border">
    <div class="row my-3">
      <div class="col-12 col-md-3 d-flex align-items-center justify-content-center ml-md-5">
        <%= image_tag(@expert.image, size: 200, class: "img-fluid px-md-2") %>
      </div>
      <div class="col-12 col-md-6 text-black-50 d-flex flex-column
         justify-content-center align-items-center align-items-md-start px-4">
        <h4 class="text-secondary">
          <%= @expert.category.name %>
        </h4>
        <p><strong><%= @expert.level.name if @expert.level.present? %></strong></p>
        <div class="d-inline-block">
          <span class="badge rounded-pill bg-success"><%= @expert.experience.presence || 0 %></span>
          <span> лет опыта</span>
        </div>
        <p><%= @expert.description %></p>
      </div>
      <div class="col-12 col-md-3 d-flex flex-column justify-content-around">
        <div class="mx-2 ">
          <div class="my-2">
            <p>Рейтинг <i class='fas fa-star fa-lg gold-star'></i><%= @expert.rating %></p>
            <p>Количество отзывов: <%= @expert.comments.count %></p>
            <span>Рекомендации:
            <i class="fas fa-thumbs-up fa-lg text-success px-1"></i><%= recommendent_count(true) %>
              <i class="fas fa-thumbs-down fa-lg text-danger px-1"></i><%= recommendent_count(false) %>
          </span>
          </div>
          <%= link_to(new_expert_event_path(@expert), method: :get, class: "btn btn-success w-100 mt-3") do %>
            <i class="fa fa-calendar mx-2"></i>Записаться
          <% end if current_user.patient? %>
          <%= button_tag data: { toggle: "modal",
                                 target: ".bd-example-modal-lg-#{@expert.id}" },
                         class: "btn btn-primary text-white w-100 mt-3" do %>
            <i class="fas fa-phone-alt mx-2"></i>Контакты
          <% end %>
        </div>
        <%= render 'modal_contact', expert: @expert %>
      </div>
    </div>
    <div class="row m-3 text-black-50">
      <h5 class="text-secondary fs-5">Образование</h5>
      <p><%= @expert.education.presence || "Врач не предоставил эту информацию" %></p>
      <h5 class="text-secondary fs-5">Дополнительное образование</h5>
      <p><%= @expert.additional_education.presence || "Врач не предоставил эту информацию" %></p>
      <h5 class="text-secondary fs-5">Выполняет процедуры</h5>
      <p><%= @expert.procedure.presence || "Врач не предоставил эту информацию" %></p>
    </div>
    <div class="bg-primary card-border pt-1 text-white">
      <%= render partial: "users/doctor_schedule", locals: { expert: @expert } %>
    </div>
  </div>
  <div>
    <h4 class="text-center text-primary pt-4 pb-3">Комментарии</h4>
    <%= link_to "Написать комментарий", new_comment_path(expert_id: @expert), method: :get,
                class: "btn btn-small btn-primary m-2" if current_user.patient? %>
    <% if @expert.comments.present? %>
      <div class="m-2 d-flex-column">
        <% @expert.comments.each do |comment| %>
          <div class="col- p-4 bg-white mb-3 border border-success my-3 card-border">
            <strong class="p-2">
              <%= (comment.user.card.full_name if comment.user.card.present?).presence || comment.user.email %>
            </strong>
            <strong class="text-right p-2"><%= render_stars(comment.rating) %></strong>
            <p class="p-3 my-3 border border-success bg-success card-border"><%= comment.body %></p>
            <div class="d-flex justify-content-between">
              <div class="p-2">
                <span>Рекомендация </span>
                <i class="fas fa-thumbs-<%= comment.recommendation ? "up" : "down" %>
               fa-lg text-<%= comment.recommendation ? "success" : "danger" %>"></i>
              </div>
              <div class="text-right px-1 btn-group-sm">
                <% if current_user == comment.user %>
                  <%= link_to 'Редактировать', edit_comment_path(comment), class: "btn btn-secondary" %>
                  <%= link_to 'Удалить', comment_path(comment), method: :delete,
                              class: "btn btn-danger", data: { confirm: 'Удалить комментарий?' } %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-center">Комментрии отсутствуют</p>
    <% end %>
  </div>
</div>